# Hardware configuration for ThinkPad
# Generated by 'nixos-generate-config'
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = ["xhci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc"];
      kernelModules = [];
      luks.devices = {
        "luks-43b140b6-ce81-4836-9f64-286f5ad8b210".device = "/dev/disk/by-uuid/43b140b6-ce81-4836-9f64-286f5ad8b210";
        "luks-2367f432-b059-480c-820a-12f84d964582".device = "/dev/disk/by-uuid/2367f432-b059-480c-820a-12f84d964582";
      };
    };
    kernelModules = [];
    extraModulePackages = [];
    kernelParams = [ "cfg80211.ieee80211_regdom=DE" ];
    extraModprobeConfig = ''
      options cfg80211 ieee80211_regdom=DE
    '';
  };

  hardware.wirelessRegulatoryDatabase = true;

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/a64829d4-8013-4270-9b10-dd38de2f4657";
      fsType = "ext4";
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/F1AE-9705";
      fsType = "vfat";
    };
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/01595afc-649c-471e-b0f1-0a5d0c984c8e";}
  ];

  # Enables DHCP on each ethernet and wireless interface
  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
