local theme = require("core.theme")
local c = theme.palette

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end

vim.g.colors_name = "doom-vibrant"
vim.o.termguicolors = true

local function hi(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

hi("Normal", {fg = c.fg, bg = c.bg})
hi("NormalFloat", {fg = c.fg, bg = c.bg_alt})
hi("FloatBorder", {fg = c.border, bg = c.bg_alt})
hi("SignColumn", {bg = c.bg})
hi("EndOfBuffer", {fg = c.bg})
hi("LineNr", {fg = c.comment})
hi("CursorLineNr", {fg = c.blue, bold = true})
hi("CursorLine", {bg = c.bg_cursorline})
hi("ColorColumn", {bg = c.bg_alt})
hi("Visual", {bg = c.bg_visual})
hi("Search", {fg = c.bg, bg = c.blue, bold = true})
hi("IncSearch", {fg = c.bg, bg = c.orange, bold = true})
hi("MatchParen", {fg = c.red, bold = true, underline = true})
hi("Pmenu", {fg = c.fg, bg = c.bg_alt})
hi("PmenuSel", {fg = c.bg, bg = c.blue, bold = true})
hi("PmenuSbar", {bg = c.bg_highlight})
hi("PmenuThumb", {bg = c.border})
hi("StatusLine", {fg = c.fg, bg = c.bg_alt})
hi("StatusLineNC", {fg = c.comment, bg = c.bg_alt})
hi("VertSplit", {fg = c.bg, bg = c.bg})
hi("WinSeparator", {fg = c.bg, bg = c.bg})
hi("TabLine", {fg = c.comment, bg = c.bg_alt})
hi("TabLineSel", {fg = c.fg, bg = c.bg})

hi("Comment", {fg = c.comment, italic = true})
hi("Constant", {fg = c.violet})
hi("String", {fg = c.green})
hi("Character", {fg = c.green})
hi("Number", {fg = c.orange})
hi("Boolean", {fg = c.orange})
hi("Float", {fg = c.orange})
hi("Identifier", {fg = c.magenta})
hi("Function", {fg = c.cyan, italic = true})
hi("Statement", {fg = c.blue})
hi("Conditional", {fg = c.blue})
hi("Repeat", {fg = c.blue})
hi("Operator", {fg = c.magenta})
hi("Keyword", {fg = c.blue})
hi("PreProc", {fg = c.magenta})
hi("Type", {fg = c.yellow})
hi("Special", {fg = c.magenta})
hi("Underlined", {fg = c.blue, underline = true})
hi("Error", {fg = c.red})
hi("Todo", {fg = c.red, bold = true})

hi("DiagnosticError", {fg = c.red})
hi("DiagnosticWarn", {fg = c.yellow})
hi("DiagnosticInfo", {fg = c.green})
hi("DiagnosticHint", {fg = c.cyan})
hi("DiagnosticUnderlineError", {undercurl = true, sp = c.red})
hi("DiagnosticUnderlineWarn", {undercurl = true, sp = c.yellow})
hi("DiagnosticUnderlineInfo", {undercurl = true, sp = c.green})
hi("DiagnosticUnderlineHint", {undercurl = true, sp = c.cyan})

hi("GitSignsAdd", {fg = c.green})
hi("GitSignsChange", {fg = c.yellow})
hi("GitSignsDelete", {fg = c.red})

hi("TelescopeNormal", {fg = c.fg, bg = c.bg_alt})
hi("TelescopeBorder", {fg = c.border, bg = c.bg_alt})
hi("TelescopePromptNormal", {fg = c.fg, bg = c.bg_alt})
hi("TelescopePromptBorder", {fg = c.border, bg = c.bg_alt})
hi("TelescopeSelection", {bg = c.bg_highlight, bold = true})
hi("TelescopeMatching", {fg = c.blue, bold = true})

hi("WhichKey", {fg = c.blue})
hi("WhichKeyGroup", {fg = c.magenta})
hi("WhichKeyDesc", {fg = c.cyan})

hi("@comment", {link = "Comment"})
hi("@string", {link = "String"})
hi("@number", {link = "Number"})
hi("@boolean", {link = "Boolean"})
hi("@function", {link = "Function"})
hi("@keyword", {link = "Keyword"})
hi("@type", {link = "Type"})
hi("@operator", {link = "Operator"})
